archimista/config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
# Upgrade 2.2.0 inizio
      post :units
# Upgrade 2.2.0 fine
    end
  end

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

archimista/app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource
# Upgrade 2.2.0 inizio
  skip_load_and_authorize_resource :only => [ :new ]
# Upgrade 2.2.0 fine

  def index
# Upgrade 2.0.0 inizio
#    @users = User.accessible_by(current_ability, :manage).all(:order => "group_id, username", :include => :group)
# Upgrade 2.2.0 inizio
#    @users = User.accessible_by(current_ability, :manage).includes(:group).order("group_id, username")
    @users = User.accessible_by(current_ability, :manage).includes(:rel_user_groups).order("rel_user_groups.group_id, username")
# Upgrade 2.2.0 fine
# Upgrade 2.0.0 fine
    @active_users = @users.select { |u| u.active? }
    @inactive_users = @users.select { |u| u.active? == false }
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
# Upgrade 2.0.0 inizio Strong parameters
#    @user = User.new(params[:user])
    @user = User.new(user_params)
# Upgrade 2.0.0 fine

    if @user.save
      redirect_to(users_url, :notice => t('devise.messages.create_ok'))
    else
      render :action => "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
# Upgrade 2.0.0 inizio Strong parameters
=begin
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      if current_user.is_at_least_admin?
        redirect_to(users_url, :notice => t('devise.messages.save_ok'))
      else
        redirect_to(root_url, :notice => t('devise.messages.save_ok'))
      end
    else
      render :action => "edit"
    end
=end
#    @user.update(user_params)
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
# Upgrade 2.2.0 inizio
=begin
      if current_user.is_at_least_admin?
        redirect_to(users_url, :notice => t('devise.messages.save_ok'))
      else
        redirect_to(root_url, :notice => t('devise.messages.save_ok'))
      end
=end
      target_url = ""
      @user.rel_user_groups.each do |rug|
        if current_user.is_at_least_admin?(rug.group_id)
          target_url = users_url
        end
      end
      if target_url == "" then target_url = root_url end
      redirect_to(target_url, :notice => t('devise.messages.save_ok'))
# Upgrade 2.2.0 fine
    else
      render :action => "edit"
    end
# Upgrade 2.0.0 fine
  end

  def toggle_active
    @user = User.find(params[:id])
    @user.toggle!(:active)

    redirect_to(users_url, :notice => t('devise.messages.save_ok'))
  end

# Upgrade 2.0.0 inizio Strong parameters
  private
    def user_params
# Upgrade 2.2.0 inizio
=begin
      wrk_params = params.dup
      rugas = wrk_params[:user][:rel_user_groups_attributes]
      wrk_params[:user].delete :rel_user_groups_attributes

      idx = 0
      rugas_new = {}
      rugas.each do |ruga|
        if str2int(ruga[1][:id]) > 0
          rugas_new = rugas_new.merge!({"#{idx}" => ruga[1]})
          idx = idx + 1
        end
      end
      wrk_params[:user].merge!(:rel_user_groups_attributes => rugas_new)
      params = wrk_params
=end
# Upgrade 2.2.0 fine
      params.require(:user).permit!
    end
# Upgrade 2.0.0 fine

end

archimista/app/views/users/_form.html.erb
<%= render :partial => "shared/generic_error_message", object: @user, as: "object"  %>

<div class="span8">
<%= form_for @user, :html => { :id => "user-form", :class => "form-horizontal well" } do |f| %>
  <div class="control-group">
    <%= f.label :username, raw(required_marker + t('devise.attributes.username')), :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :username %>
      <p class="help-block"><%= t('devise.registrations.username_characters') %></p>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, raw(required_marker + t('first_name')), :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, raw(required_marker + t('last_name')), :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qualifier, t('qualifier'), :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :qualifier %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, raw(required_marker + t('email')), :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, raw(required_marker + t('devise.attributes.password')), :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password %>
      <% unless @user.new_record? %>
        <p class="help-block"><%= t('devise.registrations.keep_current_password') %></p>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, raw(required_marker + t('devise.attributes.password_confirmation')), :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

<%# Upgrade 2.2.0 inizio %>
  <div class="row" style="margin-left: 10px;">
    <h3 class="row-header">Gruppi associati all'utente</h3>
    <div>
      <%
        if current_user.is_superadmin?
          groups = Group.order(:id)
        else
          groups = current_user.groups
        end
      %>
      <table class="table table-sortable">
        <tr>
          <th class="user_groups_column"><%= t('devise.attributes.group_id') %></th>
          <th><%= t('devise.attributes.role') %></th>
        </tr>
        <% groups.each_with_index do |group, index| %>
          <%
            rug = @user.rel_user_groups_search_by_group_id(group.id)
            target_user_role = if rug.nil? then "" else rug.role end
            rug_id = if rug.nil? then (Time.now.to_i + index).to_s else rug.id end
            target_inst_id = if rug.nil? then rug_id else index end
          %>
          <tr>
            <td class="user_groups_column"><%= group.name %></td>
            <td>
              <% if @user != current_user %>
                <% if current_user.is_superadmin? || current_user.is_at_least_admin?(group.id) %>
                  <%
                    if current_user.is_superadmin?
                      usable_roles = User.known_roles(true)
                    else
                      current_user_role = current_user.role(group.id)
                      if current_user_role == "" then current_user_role = "admin" end
                      usable_roles = User.filter_roles_for(current_user_role, true)
                    end
                  %>
                  <% if !rug.nil? %>
                    <input type="hidden" id="user_rel_user_groups_attributes_<%= target_inst_id%>_id" name="user[rel_user_groups_attributes][<%= target_inst_id%>][id]" value ="<%= rug_id %>"/>
                  <% end %>

                  <select id="user_rel_user_groups_attributes_<%= target_inst_id%>_role" name="user[rel_user_groups_attributes][<%= target_inst_id%>][role]" class="user_group_role">
                    <% usable_roles.each_with_index do |r, role_index| %>
                      <%
                        if target_user_role == ""
                          if role_index == 0
                            html_selected_clause = "selected=selected"
                          else
                            html_selected_clause = ""
                          end
                        else
                          if r == target_user_role
                            html_selected_clause = "selected=selected"
                          else
                            html_selected_clause = ""
                          end
                        end
                      %>
                      <option value="<%= r %>" <%= html_selected_clause %>><%= r %></option>
                    <% end %>
                  </select>

                  <input type="hidden" id="user_rel_user_groups_attributes_<%= target_inst_id%>_group_id" name="user[rel_user_groups_attributes][<%= target_inst_id%>][group_id]" value ="<%= group.id %>"/>

                  <% if current_user.is_superadmin? || current_user.is_at_least_admin?(group.id) %>
                    <input type="hidden" id="user_rel_user_groups_attributes_<%= target_inst_id%>_destroy" name="user[rel_user_groups_attributes][<%= target_inst_id%>][_destroy]" value =""/>
                  <% end %>
                <% else %>
                  <%#= f.text_field :role, :value => @user.role(group.id), :class => "disabled" %>
                  <input type="text" class="disabled" value="<%= @user.role(group.id) %>" disabled="disabled" />
                <% end %>
              <% else %>
                <%#= f.text_field :role, :value => @user.role(group.id), :class => "disabled" %>
                <input type="text" class="disabled" value="<%= @user.role(group.id) %>" disabled="disabled" />
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit @user.new_record? ? t('create_user') : t('save'), :class => "btn btn-primary" %>
    oppure <%= link_to t('cancel'), current_user.is_at_least_admin?(current_user.rel_user_groups[0].group_id) ? users_path : root_path %>
  </div>

<%# Upgrade 2.2.0 fine %>


<% end %>

</div>

archimista/app/views/users/_user.html.erb
<tr>
  <td><%= link_to_unless(user.is_superadmin?, user.username, edit_user_path(user)) %></td>
  <td><%= mail_to user.email, raw('<i class="icon-envelope" style="opacity: 0.7;" title="' + user.email + '"></i>') %>
  <%= user.full_name %> <%#= "(#{user.qualifier})" if user.qualifier.present? %></td>
  <td><%= raw(user.name_and_role_of_groups("<br/>")) %></td>
  <td>
    <% if user.active? %>
      <%= link_to_unless(current_user == user || user.is_superadmin?, t('deactivate'), toggle_active_user_path(user), :method => :put, :class => "btn btn-mini") do |text| '' end %>
    <% else %>
      <%= link_to_unless(current_user == user, t('activate'), toggle_active_user_path(user), :method => :put, :class => "btn btn-mini") do |text| '' end %>
    <% end %>
  </td>
</tr>

archimista/app/views/users/edit.html.erb
<% content_for :status_bar do %>
  <h2>
    <% if current_user == @user %>
      Modifica profilo
    <% else %>
      <%= status_bar_context %>
    <% end %>
  </h2>
<%# Upgrade 2.2.0 inizio %>
  <%# if current_user.is_at_least_admin? %>
  <% if current_user.is_superadmin? || current_user.is_admin_for_some_group? %>
    <div id="links">
      <%= link_to_index t('index_users'), users_path %>
    </div>
  <% end %>
<%# Upgrade 2.2.0 fine %>
<% end %>

<%= render :partial => "form" %>

archimista/app/views/users/index.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <% if current_user.is_superadmin? %>
    <div id="links">
      <%= link_to "Vai alla lista gruppi", groups_path %>
    </div>
  <% end %>
<% end %>

<div class="span12">
<div id="index-controls">
  <%= link_to t('new'), new_user_path, { :class => "btn btn-small new" } %>
</div>
<p>
  <%= link_to_unless(params[:view].nil?, "Attivi", users_path) %>
  <span class='muted'>(<%= @active_users.length %>)</span> |
  <%= link_to_unless(params[:view] == "inactive" || @inactive_users.length == 0, "Non attivi", users_path(:view => "inactive")) %>
  <span class='muted'>(<%= @inactive_users.length %>)</span>
</p>

<table class="table table-striped">
  <thead>
  <tr>
    <th class="span2"><%= t('devise.attributes.username') %></th>
    <th class="span4"><%= t('devise.attributes.full_name') %></th>
    <th class="span4"><%= t('devise.attributes.group_id') + "/" + t('devise.attributes.role') %></th>
    <th class="span1">&nbsp;</th>
  </tr>
  </thead>
  <tbody>
    <%= render :partial => "user", :collection => params[:view] == "inactive" ? @inactive_users : @active_users %>
  </tbody>
</table>
</div>

archimista/app/views/users/new.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_users'), users_path %>
  </div>
<% end %>

<%= render :partial => "form" %>