archimista/config/routes.rb
# Upgrade 2.0.0 inizio
Rails.application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :users do
    put 'toggle_active', on: :member
  end

  # Polymorphic resources (must be here, prior to parent resources)
  resources :digital_objects, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end
  resources :group_images, :only => [:destroy] do
    collection do
      get :all
      get :disabled
      get :sort
      get :bulk_destroy
    end
  end

  resources :groups do
    resources :group_carousel_images, :except => [:show, :destroy], :controller => "group_images", :type => "carousel"
    resources :group_logo_images, :except => [:show, :destroy], :controller => "group_images", :type => "logo"
  end

  resources :fonds, :except => [:new] do
    member do
      get    :tree
      get    :treeview
      put    :ajax_update
      patch  :ajax_update
      put    :rename
      put    :move
      get    :merge_with
      post   :merge
      get    :split_fond
      post   :split
      get    :trash
      get    :trashed_subtree
      put    :move_to_trash
      put    :restore_subtree
      delete :destroy_subtree
      put    :publish
      put    :unpublish
    end
    collection do
      get  :save_a_tree
      post :saving_the_tree
      get  :list
      post :ajax_create
    end

    resources :units do
      collection do
        get  :gridview
        post :gridview
        get  :grid
        post :add_rows
        put  :remove_rows
        put  :reorder_rows
# Upgrade 2.1.0 inizio
#        get  :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :units, :except => [:new] do
    member do
      put   :ajax_update
      patch :ajax_update
      get   :render_full_path
      get   :preferred_event
      get   :textfield_form
      put   :update_event
# Upgrade 2.1.0 inizio
#      get   :edit_iccd
#      get   :show_iccd
# Upgrade 2.1.0 fine
      get   :move
      post  :move_down
      post  :move_up
    end
    collection do
      get :list_oa_mtc
      get :list_oa_ogtd
      get :list_bdm_ogtd
      get :list_bdm_mtcm
      get :list_bdm_mtct
# Upgrade 2.1.0 inizio
      get :sc2_voc_list
# Upgrade 2.1.0 fine
      put :classify
    end

    # OPTIMIZE: rinominare in subunits ?
    resources :children, :controller => 'units', :only => 'new' do
      collection do
# Upgrade 2.1.0 inizio
#        get :new_iccd
# Upgrade 2.1.0 fine
      end
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :creators do
    collection do 
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :custodians do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :sources do
    collection do
      get :list
    end
    resources :digital_objects, :except => [:show, :destroy]
  end

  resources :institutions do
    collection do
      get :list
    end
  end

  resources :document_forms do
    collection do
      get :list
    end
  end

  resources :projects do
    collection do
      get :list
      put :publish
      put :unpublish
    end
  end

  resources :editors do
    collection do
      get  :list
      get  :modal_new
      post :modal_create
    end
  end

  # Strumenti
  resources :headings do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :anagraphics do
    collection do
      get  :import_csv
      post :preview_csv
      post :save_csv
      get  :list
      get  :modal_new
      post :modal_create
      get  :modal_link
      get  :ajax_list
      post :ajax_remove
      post :ajax_link
    end
  end

  resources :reports, :only => [:index] do
    member do
      get  :dashboard
      get  :summary
      get  :inventory
      post :inventory
      get  :creators
      get  :custodians
      get  :labels
      get  :units
      get  :custodian
      post :custodian
      get  :project
      post :project
    end
    collection do
      get :download
    end
  end

  resources :quality_checks, :only => [:index] do
    member do
      get :fond
      get :creator
      get :custodian
    end
  end

# Upgrade 3.0.0 inizio
resources :multiple_occours, :only => [:index] do
    member do
      post :merge
    end
  end
# Upgrade 3.0.0 fine

  resources :imports, :only => [:index, :new, :create, :destroy]
  resources :exports, :only => [:index] do
    collection do
      get :download
      get :xml
# Upgrade 2.2.0 inizio
      post :units
# Upgrade 2.2.0 fine
    end
  end

  # Vocabolari
  resources :vocabularies, :only => [:index]

  resources :creator_corporate_types, :only => [:index]
  resources :custodian_types, :only => [:index]
  resources :source_types, :only => [:index]

  resources :activities, :only => [:index] do
    collection do
      get :list
    end
  end
  resources :places, :only => [:index] do
    collection do
      get :cities
      get :countries
    end
  end
  resources :langs, :only => [:index]

  # Non-Resourceful Routes
  root :to => 'site#dashboard'
  resources :about, :only => [:index], :to => "site#about"
  match :parse_textile, :only => [:index], :to => "site#parse_textile", :via => [:get, :post]

end

# Upgrade 2.0.0 fine

archimista/app/models/group.rb
class Group < ActiveRecord::Base

  extend Cleaner

  before_destroy :is_empty?
# Upgrade 2.2.0 inizio
#  has_many :users
  has_many :rel_user_groups, dependent: :destroy
  has_many :users, :through => :rel_user_groups
# Upgrade 2.2.0 fine

# Upgrade 2.0.0 inizio
  has_many :carousel_images, :dependent => :destroy, :class_name => 'GroupCarouselImage', :foreign_key => "related_group_id"
  has_many :logo_images, :dependent => :destroy, :class_name => 'GroupLogoImage', :foreign_key => "related_group_id"
# Upgrade 2.0.0 fine

  validates_presence_of :name
  validates_uniqueness_of :name
  squished_fields :name

# Upgrade 2.1.0 inizio
  validates_presence_of :short_name
  validates_length_of :short_name, :maximum => 30, :message => :too_long_value
  validates_uniqueness_of :short_name, :message => :not_unique_value
  validates_format_of :short_name, :with => /\A[a-zA-Z]([a-zA-Z0-9_-]*)\z/, :message => :illegal_format
# Upgrade 2.1.0 fine

  def is_empty?
# Upgrade 2.2.0 inizio
#    users.empty?
    rel_user_groups.empty?
# Upgrade 2.2.0 fine
  end

  def self.filter(group=1)
# Upgrade 2.0.0 inizio
=begin
    case group
    when 1 then
      self.all(:order => :name).map{|g| [ g.name, g.id ] }
    else
      self.all(:conditions => "id = #{group}", :order => :name).map {|g| [ g.name, g.id ] }
    end
=end
    case group
    when 1 then
      self.order(:name).map{|g| [ g.name, g.id ] }
    else
      self.where("id = #{group}").order(:name).map {|g| [ g.name, g.id ] }
    end
# Upgrade 2.0.0 fine
  end

end

archimista/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  helper_method :sort_column

  load_and_authorize_resource

  def index
# Upgrade 2.0.0 inizio
#    @groups = Group.accessible_by(current_ability, :manage).all(:order => lower_sort_column + ' ' + sort_direction)
#    @assets = DigitalObject.sum(:asset_file_size, :group => "group_id")

    @groups = Group.accessible_by(current_ability, :manage).order(lower_sort_column + ' ' + sort_direction)
    @assets = DigitalObject.group("group_id").sum(:asset_file_size)
# Upgrade 2.0.0 fine
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
# Upgrade 2.0.0 inizio Strong parameters
#    @group = Group.new(params[:group])
    @group = Group.new(group_params)
# Upgrade 2.0.0 fine

    if @group.save
      redirect_to(groups_url, :notice => "Creato il gruppo: #{@group.name}")
    else
      render :action => "new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

# Upgrade 2.0.0 inizio Strong parameters
=begin
    if @group.update_attributes(params[:group])
      redirect_to(groups_url, :notice => "Gruppo aggiornato.")
    else
      render :action => "edit"
    end
=end
    if @group.update_attributes(group_params)
      redirect_to(groups_url, :notice => "Gruppo aggiornato.")
    else
      render :action => "edit"
    end
# Upgrade 2.0.0 fine
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to(groups_url, :notice => "Eliminato il gruppo: #{@group.name}")
  end

  private

  def sort_column
    params[:sort] || "created_at"
  end

# Upgrade 2.0.0 inizio Strong parameters
  def group_params
    params.require(:group).permit!
  end
# Upgrade 2.0.0 fine

end

archimista/app/views/groups/_form.html.erb
<%# Upgrade 2.0.0 inizio %>
<%#= render :partial => "shared/generic_error_message", :object => @group %>
<%= render :partial => "shared/generic_error_message", object: @group, as: "object"%>
<%# Upgrade 2.0.0 fine %>

<div class="span9">
<%# TAI aggiunto = prima di form_for %>
<%= form_for @group do |f| %>
<%# TAI aggiunto raw() %>
<%# TAI aggiunto parametro per specificare nome e caption, cambiato t('name') in t('group_name') %>
  <%= f.label :name, raw(t('group_name') + required_marker) %>
<%# Upgrade 2.1.0 inizio %>
  <% if @group.name == "default" %>
    <%= f.text_field :name, :class => "span6", :readonly => true %>
  <% else %>
    <%= f.text_field :name, :class => "span6" %>
  <% end %>
<%# Upgrade 2.1.0 fine %>

<%# Upgrade 2.1.0 inizio %>
  <%= f.label :short_name, raw(t('group_short_name') + required_marker) %>
  <%= f.text_field :short_name, :class => "span6" %>

  <%= f.label :site_caption, t('group_site_caption') %>
  <%= f.text_field :site_caption, :class => "span6" %>

  <%= f.label :description, t('group_description') %>
  <%= f.text_area :description, :class => "long-content span6" %>

  <%= f.label :credits_link_caption, t('group_credits_link_caption') %>
  <%= f.text_field :credits_link_caption, :class => "span6" %>

  <%= f.label :credits, t('group_credits') %>
  <%= f.text_area :credits, :class => "long-content span6" %>

  <% if IM_ENABLED %>
    <div class="well" style="padding-top: 5px; padding-bottom: 5px;">
      <% if %w[new create].include?(action_name) %>
        <span class="muted"><%= t('group_carousel_images') %></span>
      <% else %>
        <%= link_to_carousel_images_by_count(@group.carousel_images.count, t('group_carousel_images'), @group) %>
        <%= link_to_carousel_images_by_count(@group.carousel_images.count, @group.carousel_images.count, @group, :class => "badge") unless @group.carousel_images.count == 0 %>
      <% end %>
    </div>
  <% else %>
    <div id="digital-objects-warning" class="well">
      <span class="muted"><%= t('group_carousel_images') %></span>
    </div>
  <% end %>

  <% if IM_ENABLED %>
    <div class="well" style="padding-top: 5px; padding-bottom: 5px;">
      <% if %w[new create].include?(action_name) %>
        <span class="muted"><%= t('group_logo_images') %></span>
      <% else %>
        <%= link_to_logo_images_by_count(@group.logo_images.count, t('group_logo_images'), @group) %>
        <%= link_to_logo_images_by_count(@group.logo_images.count, @group.logo_images.count, @group, :class => "badge") unless @group.logo_images.count == 0 %>
      <% end %>
    </div>
  <% else %>
    <div id="digital-objects-warning" class="well">
      <span class="muted"><%= t('group_logo_images') %></span>
    </div>
  <% end %>

<%# Upgrade 2.1.0 fine %>

  <p><%= f.submit @group.new_record? ? t('create_group') : t('save'), :class => "btn btn-primary" %></p>
<% end %>
</div>

archimista/app/views/groups/edit.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_groups'), groups_path %>
  </div>
<% end %>

<%= render :partial => "form" %>

archimista/app/views/groups/index.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
<%# Upgrade 2.2.0 inizio %>
  <%# if current_user.is_at_least_admin? %>
  <% if current_user.is_superadmin? || current_user.is_admin_for_some_group? %>
    <div id="links">
      <%= link_to "Vai alla lista utenti", users_path %>
    </div>
  <% end %>
<%# Upgrade 2.2.0 fine %>
<% end %>

<div class="span12">

<div id="index-controls">
<%# Upgrade 2.1.0 inizio %>
  <%#= link_to t('new'), new_group_path, { :class => "btn btn-small new" } %>
  <% if current_ability.can?(:create, Group) %>
    <%= link_to t('new'), new_group_path, { :class => "btn btn-small new" } %>
  <% end %>
<%# Upgrade 2.1.0 fine %>
</div>

<div class="row">
  <div class="span12">
    <table class="table table-sortable">
      <tr>
        <th><%= sortable("name", t('name')) %></th>
        <th class="center"><%= t('users_count') %></th>
        <th class="center"><%= t('digital_objects') %></th>
        <th><%= sortable("created_at", t('created_at')) %></th>
        <th>&nbsp;</th>
      </tr>
      <% @groups.each do |group| %>
      <tr>
        <td>
<%# Upgrade 2.1.0 inizio %>
          <%#= link_to_unless(group.name == 'default', group.name, edit_group_path(group)) %>
          <%= link_to group.name, edit_group_path(group) %>
<%# Upgrade 2.1.0 fine %>
        </td>
        <td class="center">
          <%= group.users.select {|u| u.active == true }.size %> / <%= group.users.size %>
        </td>
<%# TAI aggiunto raw() %>
        <td class="center"><%= number_to_human_size(@assets[group.id]) || raw("&mdash;") %></td>
        <td><%= l group.created_at, :format => :long %></td>
        <td>
          <%= link_to_if(group.is_empty?, t('destroy'), group, :method => :delete) do |text| '' end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

</div>

archimista/app/views/groups/new.html.erb
<% content_for :status_bar do %>
  <h2><%= status_bar_context %></h2>
  <div id="links">
    <%= link_to_index t('index_groups'), groups_path %>
  </div>
<% end %>
<%= render :partial => "form" %>